openapi: 3.0.0
info:
  title: Tavily Search API
  description: API for performing searches using Tavily
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /api/tavily:
    post:
      summary: 执行搜索查询
      description: 根据提供的查询词返回相关搜索结果
      operationId: searchTavily
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: 搜索查询词
                  example: "哪吒2"
      responses:
        '200':
          description: 成功返回搜索结果
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: 状态码，200表示成功
                    example: 200
                  success:
                    type: boolean
                    description: 请求是否成功
                    example: true
                  data:
                    type: object
                    properties:
                      query:
                        type: string
                        description: 原始查询词
                        example: "哪吒2"
                      responseTime:
                        type: number
                        format: float
                        description: 响应时间（秒）
                        example: 1.36
                      images:
                        type: array
                        description: 图片结果列表
                        items:
                          type: object
                      results:
                        type: array
                        description: 搜索结果列表
                        items:
                          type: object
                          properties:
                            title:
                              type: string
                              description: 结果标题
                              example: "《哪吒2》延长上映至3月30日"
                            url:
                              type: string
                              description: 结果链接
                              example: "https://www.zaobao.com.sg/realtime/china/story20250219-5899501"
                            content:
                              type: string
                              description: 结果内容摘要
                            rawContent:
                              type: string
                              nullable: true
                              description: 原始内容
                            score:
                              type: number
                              format: float
                              description: 相关度评分
                              example: 0.71040785
        '400':
          description: 请求参数错误
        '500':
          description: 服务器内部错误